platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet
    tag: '2.0.0-sdk'

inputs:
  - name: pal-tracker

outputs:
  - name: build-output

run:
  path: bash
  args:
  - -exc
  - |
  
    mkdir -p build-output/src/PalTracker
    cp pal-tracker/manifest.yml build-output
    
    dotnet test pal-tracker/test/PalTrackerTests/PalTrackerTests.csproj

    dotnet publish pal-tracker/src/PalTracker --configuration Release
    cp -r pal-tracker/src/PalTracker/* build-output/src/PalTracker

